name: excel2l10n
description: A tool to convert excel to l10n files.
version: 0.1.5
repository: https://github.com/huanghui1998hhh/excel2l10n

environment:
  sdk: ^3.3.0

dependencies:
  args: ^2.7.0
  dart_style: ^3.1.3
  dio: ^5.9.0
  meta: ^1.17.0
  pub_semver: ^2.2.0
  yaml: ^3.1.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0
